    version: "0.1.0"
    pre_ci_boot: 
        image: 10.0.0.6:5000/piggymetrics/piggyjava 
        tag: latest

    ci:
        - cp   config/alaudaci/settings.xml  /etc/maven/
        - cd  config
        - mvn clean package 
